#!/usr/bin/env python
# coding: utf-8


# Символы Юникод


# Autogenerated with DRAKON Editor 1.31
class EmbedData(object):



    def __init__(self, data):
        #item 72
        self._data = data
        self.now = 0
        self.len = len(data)


    def __len__(self):
        #item 80
        return self.len


    def available(self):
        #item 101
        return self.len - self.now


    def read(self):
        #item 88
        self.now += 1
        #item 91
        if self.now > self.len:
            #item 94
            return 0
        else:
            #item 95
            return ord(self._data[self.now - 1])


