#!/usr/bin/env python
# coding: utf-8


# Символы Юникод


# Autogenerated with DRAKON Editor 1.31
class FilteredCollection(object):
	import ListNotEnough



    def __init__(self, l, filter_func):
        #item 72
        self.iterator = l
        self.filter_func = filter_func
        self.now = 0


    def offer(self, count=1):
        #item 80
        result = []
        while True:
            #item 83
            if count:
                pass
            else:
                break
            while True:
                #item 86
                if self.now < len(self.iterator) and not self.filter_func(self.iterator[self.now]):
                    pass
                else:
                    break
                #item 89
                self.now += 1
            #item 91
            if self.now < len(self.iterator):
                #item 94
                count -= 1
                result.append(self.iterator[self.now])
                self.now += 1
            else:
                #item 95
                raise FilteredCollection.ListNotEnough(count)
        #item 97
        return result


