#!/usr/bin/env python
# coding: utf-8

# Символы Юникод

JPEG_NATURAL_ORDER = [0, 1, 8, 16, 9, 2, 3, 10, 17, 24, 32, 25, 18, 11, 4, 5, 12, 19, 26, 33, 40, 48, 41, 34, 27, 20, 13, 6, 7,
        14, 21, 28, 35, 42, 49, 56, 57, 50, 43, 36, 29, 22, 15, 23, 30, 37, 44, 51, 58, 59, 52, 45, 38, 31, 39, 46,
        53, 60, 61, 54, 47, 55, 62, 63]

import BreakException
import EmbedData
import Permutation

# Autogenerated with DRAKON Editor 1.31

def create_array(default_value=None, *args):
    #item 80
    if len(args) and args[0]:
        #item 84
        return [create_array(default_value, *args[1:]) for i in range(args[0])]
    else:
        #item 83
        return default_value


