#!/usr/bin/env python
# coding: utf-8



# Символы Юникод



# Autogenerated with DRAKON Editor 1.31
class ListNotEnough(Exception):



    def __init__(self, count):
        #item 72
        super(FilteredCollection.ListNotEnough, self).__init__('sorry list is not enough to provide %d elements' % count)


